version: '3'

services:
    nginx:
        build: ./nginx
        container_name: nginx
        # volumes:
        #   - ./nginx/:/etc/nginx/nginx.conf
            # - ./frontend/static:/var/www/
        networks:
            - thenet
        ports:
            - ${NGINX_PORT}:80
        depends_on:
            - app
            - frontend

    app:
        build: ./app
        container_name: app
        volumes:
            - ./app:/workspace/app
            - /workspace/app/node_modules
        networks:
            - thenet
        restart: always
        # unccomment for direct http://localhost:{APP_PORT}
        # ports:
        #     - ${APP_PORT}:3000
        command:
            "yarn start"
    frontend:
        build: ./frontend
        container_name: frontend
        volumes:
            - ./frontend:/workspace/frontend
            - /workspace/frontend/node_modules
        networks:
            - thenet
        restart: always
        # unccomment for direct http://localhost:{FRONTEND_PORT}
        # ports:
        #     - ${FRONTEND_PORT}:3000
        command: bash -c "yarn build && yarn preview; while true; do sleep 10; done;"

networks:
    thenet: