version: '3'

services:
    nginx:
        build: ./nginx
        container_name: nginx
        networks:
            - thenet
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
            - frontend

    app:
        build: ./app
        container_name: app
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - thenet
        restart: always
        # unccomment for direct http://localhost:{APP_PORT}
        # ports:
        #     - ${APP_PORT}:3000
        command:
            "yarn start"
    frontend:
        build: ./frontend
        container_name: frontend
        # volumes:
        #     - ./frontend:/usr/src/frontend/
        #     - /usr/src/frontend/node_modules
        networks:
            - thenet
        restart: always
        # unccomment for direct http://localhost:{FRONTEND_PORT}
        # ports:
        #     - ${FRONTEND_PORT}:4444
        command:
            "yarn start"

networks:
    thenet: